// Code generated by "stringer -type SandboxStatus .\sandbox\sandbox.go"; DO NOT EDIT.

package sandbox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotRan-0]
	_ = x[Created-1]
	_ = x[Running-2]
	_ = x[Killing-3]
	_ = x[Killed-4]
	_ = x[Finished-5]
	_ = x[MemoryConstraintExceeded-6]
	_ = x[TimeLimitExceeded-7]
	_ = x[ProvidedTestFailed-8]
	_ = x[CompilationFailed-9]
	_ = x[NonDeterministicError-10]
}

const _SandboxStatus_name = "NotRanCreatedRunningKillingKilledFinishedMemoryConstraintExceededTimeLimitExceededProvidedTestFailedCompilationFailedNonDeterministicError"

var _SandboxStatus_index = [...]uint8{0, 6, 13, 20, 27, 33, 41, 65, 82, 100, 117, 138}

func (i SandboxStatus) String() string {
	if i < 0 || i >= SandboxStatus(len(_SandboxStatus_index)-1) {
		return "SandboxStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SandboxStatus_name[_SandboxStatus_index[i]:_SandboxStatus_index[i+1]]
}
