// Code generated by "stringer -type=ContainerTestStatus"; DO NOT EDIT.

package sandbox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoTest-0]
	_ = x[TestNotRan-1]
	_ = x[TestFailed-2]
	_ = x[TestPassed-3]
}

const _ContainerTestStatus_name = "NoTestTestNotRanTestFailedTestPassed"

var _ContainerTestStatus_index = [...]uint8{0, 6, 16, 26, 36}

func (i ContainerTestStatus) String() string {
	if i < 0 || i >= ContainerTestStatus(len(_ContainerTestStatus_index)-1) {
		return "ContainerTestStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContainerTestStatus_name[_ContainerTestStatus_index[i]:_ContainerTestStatus_index[i+1]]
}
